### PR TITLE
Use relative file paths to upload files

### PR DESCRIPTION
**Pull request by pgilad**
Might be a breaking change for some users.

### CODE REVIEW

**Comment by pgilad** [comment]
any news?

**Comment by pgherveou** [comment]
sorry for the slow reply
I dont think we can merge that it will break the current behavior
if you use the relative path then you can't really publish to nested path right?

you can always use a gulp plugin like gulp-rename to update files before they are passed to the publisher

**Comment by pgherveou** [comment]
let me know what you think and feel free to reopen this ticket if you think I am wrong

**Comment by pgilad** [comment]
I have no clue as to why anyone would like to upload an absolute path to s3. For me that's counter-intuitive. If anything - absolute path should be an opt-in.

You are actually *requiring* everyone to use `gulp-rename` (or the sorts) in order to use this plugin, which suggests it uses bad defaults.

Yes I think you are wrong to close this, and a breaking change can have a major release, it happens in the coding world every day.

**Comment by pgherveou** [comment]
nobody is using absolute path nor use  gulp-rename every time
most of the time you can just use gulp src to get the files you want 

have a look at gulp.src and node-glob doc to see how to use the different options
- https://github.com/isaacs/node-glob
- https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpsrcglobs-options

also i just added a simple example in the project, have a look it might help you build your own gulp file 
```js
var fs = require('fs');
var gulp = require('gulp');
var awspublish = require('../');

var credentials = JSON.parse(fs.readFileSync('aws-credentials.json', 'utf8'));
var publisher = awspublish.create(credentials);

gulp
  .src('./examples/**/*.js')
  .pipe(publisher.publish())
  .pipe(awspublish.reporter())

// log [create] concurrent.js
// log [create] events.js
// log [create] merge-streams.js
// log [create] rename.js
// log [create] simple.js
// log [create] fixtures/bar.js
// log [create] fixtures/foo.js
// log [create] public/assets/js/foo.js

gulp
   .src('examples/fixtures/*.js')
   .pipe(publisher.publish())
   .pipe(awspublish.reporter())

// log [create]   bar.js
// log [create]   foo.js
```

**Comment by pgilad** [comment]
Your solution would only work with a glob, but if I want to use specific files, this won't work.
This all comes around to workarounds.

I have worked with (and made) a lot of gulp plugins, and rarely saw any that required the usage of absolute paths. This one is **not** an exception. But since it seems you guys are committed to sticking to this awkward interface, I can create my own modules.

**Comment by pgherveou** [comment]
No need to be aggressive about it!

actually I had a closer look at your pr and 
your change can actually be merged, since most of the time the change will return the same result

```js
file = new File({
  base: '/',
  path: '/test/hello.txt',
  contents: new Buffer('hello world 2')
})

file.path.substring(file.base.length).replace(/\\/g, '/') === file.relative.replace(/\\/g, '/')
```
can you explain with an example your use case, or best a failing test? 
so we can see what need to be to fixed here.

Also you might want to have a look at this module https://www.npmjs.com/package/gulp-awspublish-router, if you need file specific routing rules

**Comment by pgilad** [comment]
This is what I use (with a custom gulp-awspublish):
```js
    var oneMonthHeaders = {
        'Cache-Control': 'max-age=2628000,s-maxage=2628000,no-transform,public'
    };
    var tenMinutesHeaders = {
        'Cache-Control': 'max-age=600,s-maxage=900,no-transform,public'
    };
    var noCacheHeaders = {
        'Cache-Control': 'max-age=0,no-transform,public'
    };

    gulp.src('./build/{css,js}/*', {
            base: './build',
        })
        .pipe(plugins.awspublish.gzip())
        .pipe(publisher.publish(oneMonthHeaders))
        .pipe(plugins.awspublish.reporter());

    gulp.src(['./build/{,img/}*', '!./build/index.html'], {
            base: './build',
        })
        .pipe(plugins.awspublish.gzip())
        .pipe(publisher.publish(tenMinutesHeaders))
        .pipe(plugins.awspublish.reporter());

    gulp.src('./build/index.html', {
            base: './build',
        })
        .pipe(plugins.awspublish.gzip())
        .pipe(publisher.publish(noCacheHeaders))
        .pipe(plugins.awspublish.reporter());
```

Without using `file.relative`, it uploads absolute paths.

**Comment by pgherveou** [comment]
ok, I am good to merge your change, 
could you just  extract what's going wrong here into a new test case 
(https://github.com/pgherveou/gulp-awspublish/blob/master/test/index.js)

**Comment by pgherveou** [comment]
Ok tested your failing use case, 
merging this now

**Comment by pgilad** [comment]
Great to hear. Please notice it might be a breaking change for some users, so I would bump the major version if I would release it...

**Comment by pgherveou** [comment]
i bumped and released  3.0.0

**Comment by pgilad** [comment]
:shipit:

**Pull request merged**
