### PR TITLE
refactored to use aws-sdk instead of knox

### PR DESCRIPTION
**Pull request by mshick**
Per #32 I've refactored the module to use the aws-sdk instead of Knox.

I haven't added or removed any functionality -- just replaced Knox and dependent modules with aws-sdk and one other dependency.

I think this is worthwhile because it seems aws-sdk will have better long term support. I'd also like to add functionality that handles the `putBucketWebsite` for a more complete package, and I found that nearly impossible to do with Knox.

### CODE REVIEW

**Comment by pgherveou** [comment]
That's great, I'll have a look asap

**Comment by pgherveou** [comment]
I can't make the tests works, can you have a look?
see https://github.com/pgherveou/gulp-awspublish#testing for more info

**Comment by pgherveou** [comment]
Also it looks like we dont need these lines of code anymore, 
https://github.com/pgherveou/gulp-awspublish/blob/master/lib/index.js#L29-L40
you can remove them as well

**Comment by mshick** [comment]
looking now.

**Comment by mshick** [comment]
The test will need to be updated for aws-sdk. deleteMultiple is a Knox method… I’ll see what else might be up in the test.

**Comment by mshick** [comment]
Okay, I’ve updated the tests and sorted out a few small problems. Also removed that S3Err function.

**Comment by pgherveou** [comment]
I reviewed your code and encountered some errors with the xml-stream package under node 0.10

I found a simpler solution for the sync method that make everything works under 0.10 and make things a bit more readable.

https://gist.github.com/pgherveou/ddb020679f3add7179c0

can you copy paste that to your index.js so I can merge?

**Comment by pgherveou** [comment]
also if you have a chance to update that section with the new create options that would be great!
https://github.com/pgherveou/gulp-awspublish#awspublishcreateoptions

**Comment by mshick** [comment]
Yeah, node-expat seems to have been an offender for some time now (I saw issues about those warnings going back to 2012).

Really glad you found this approach. I like it much more.

I’ll get it synced up shortly.

**Comment by mshick** [comment]
Okay, all set on both accounts.

**Pull request merged**
