### PR TITLE
Drop dependency on deprecated `gulp-util`

### LINKED ISSUE #145: Replace deprecated dependency gulp-util
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated recently. Continuing to use this dependency may prevent the use of your library with the latest release of Gulp 4 so **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is one of the most popular packages still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

### PR DESCRIPTION
**Pull request by TheDancingCode**
Closes #145

### CODE REVIEW

**Comment by pgherveou** [comment]
@TheDancingCode sorry for the late response, 
Do you mind if I add you as a collaborator on this project? If you can ensure that tests pass 
I would be happy to push a new version on npm.

**Comment by TheDancingCode** [comment]
I can't really collaborate on this project. I'm not an AWS user, so I can't run the tests I'm afraid. Do the tests not pass?

**Comment by demurgos** [comment]
@pgherveou 
The Gulp team is in the process a new organization to host popular plugins and help maintainers (`gulp-community`). If you're looking for collaborators, it may interest you. There is still some preparation needed but there should be more info soon.

Regarding the PR itself it should be safe to merge it (patch update from a semver point of view).

**Comment by pioug** [comment]
Tests are passing on my machine with a test bucket 👍 

_Though I am getting a `growlnotify` error related to `mocha` report (same error happening currently on `master`)._

I am merging and bumping. @pgherveou If you can double-check and publish after 🙏 

Thank everyone for you contribution!

**Comment by pgherveou** [comment]
Thks @pioug will do that asap

**Pull request merged**
