### PR TITLE
Add linting task

### PR DESCRIPTION
**Pull request by TheDancingCode**
I noticed that this repo has a `.jshintrc` file, but no linting task to match. This PR reinstates `JSHint` and fixes the errors that went uncaught.

### CODE REVIEW

**Comment by pgherveou** [comment]
Thanks for doing this, @pioug I think we should start using prettier for the project, this should solve most of our linting/styling issues.

**Comment by pioug** [comment]
@pgherveou Yes Prettier would be great! 

Nowadays I always use Prettier with the default config + ESLint with the  `eslint:recommended` config.   I like ESLint because it catches any nonsense JS that I write 😆 The default config is very reasonable. 

We are adding more tools but as long as we don't tune the rules, it stays low-maintenance.

**Comment by TheDancingCode** [comment]
I can do that for you if you like: add Prettier and replace JSHint wih ESLint and its recommended rules.

**Comment by pgherveou** [comment]
That would be great @TheDancingCode  !

**Pull request merged**
